class TableNames:
    BANK_MOVEMENT="bank_movements"

class EnvironmentVariableNames:
    PERSONAL_DATABASE="PERSONAL_DATABASE"
    SOURCE_EVO_FILES="SOURCE_EVO_FILES"
    SOURCE_MY_INVESTOR_FILES="SOURCE_MY_INVESTOR_FILES"
    MOVEMENTS_RESULT="MOVEMENTS_RESULT"
    REVOLUT_CSV_MONETARY="REVOLUT_CSV_MONETARY"
    REVOLUT_MONETARY_RESULT="REVOLUT_MONETARY_RESULT"
    MOVIMIENTOS_CUENTA_CORRIENTE_EVO="MOVIMIENTOS_CUENTA_CORRIENTE_EVO"
    MOVIMIENTOS_MY_INVESTOR="MOVIMIENTOS_MY_INVESTOR"

class BankNames:
    EVO="evo"
    MYINVESTOR="myinvestor"
    SABADELL="sabadell"

class BrokerNames:
    EVO="evo"
    MYINVESTOR="myinvestor"