class TableNames:
    BANK_MOVEMENT="bank_movements"
    OPERATION="operacion"
    SPLIT="split"

class EnvironmentVariableNames:
    PERSONAL_DATABASE="PERSONAL_DATABASE"
    BACKUP_FOLDER="BACKUP_FOLDER"
    SOURCE_EVO_FILES="SOURCE_EVO_FILES"
    SOURCE_MY_INVESTOR_FILES="SOURCE_MY_INVESTOR_FILES"
    MOVEMENTS_RESULT="MOVEMENTS_RESULT"
    REVOLUT_CSV_MONETARY="REVOLUT_CSV_MONETARY"
    REVOLUT_MONETARY_RESULT="REVOLUT_MONETARY_RESULT"
    MOVIMIENTOS_CUENTA_CORRIENTE_EVO="MOVIMIENTOS_CUENTA_CORRIENTE_EVO"
    MOVIMIENTOS_MY_INVESTOR="MOVIMIENTOS_MY_INVESTOR"
    MOVIMIENTOS_SABADELL="MOVIMIENTOS_SABADELL"
    JSON_BROKER_MY_INVESTOR="JSON_BROKER_MY_INVESTOR"
    JSON_BANK_MY_INVESTOR="JSON_BANK_MY_INVESTOR"
    SPLIT_PATH="SPLIT_PATH"

class BankNames:
    EVO="evo"
    MYINVESTOR="myinvestor"
    SABADELL="sabadell"

class BrokerNames:
    EVO="evo"
    MYINVESTOR="myinvestor"

class MovementTypes:
    COMPRA_VALOR="COMPRA_VALOR"
    VENTA_VALOR="VENTA_VALOR"
    DIVIDENDO="DIVIDENDO"
    TRANSFERENCIA="TRANSFERENCIA"
    INTERESES="INTERESES"